dist: trusty
language: node_js
node_js:
  - stable

script:
  - npm test
after_script:
  - npm run coveralls

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - psql -c 'drop database if exists acedms-test;' -U postgres
  - psql -c 'create database acedms-test;' -U postgres
  - NODE_ENV=test npm run migrate

services:
  - postgresql

addons:
  postgresql: "9.3"

after_success:
  - npm run coveralls

addons:
  postgresql: "9.3"
  

