sudo: required
dist: trusty
language: node_js
node_js:
  - stable
script: npm run coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database acedms_test;' -U postgres
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start




